site_name: prefect-azure

nav:
  - Home: index.md
  - Credentials: credentials.md
  - Blob Storage: blob_storage.md
  - Cosmos DB: cosmos_db.md
  - ML Datastore: ml_datastore.md
  - Container Instance Block: container_instance.md
  - Container Instance Worker: container_instance_worker.md
  - Deployments:
      - Steps: deployments/steps.md
